### ISSUE TITLE
stuck in default: Verifying Hyper-V is enabled...

### ISSUE THREAD

**Issue by petitchamp** [mystand/mystand-hyper-box#1]
I have windows 10 and hyper v. 
But when run vagrant up --provider=hyperv in a admin console , the command stuck in step 
  _==> default: Verifying Hyper-V is enabled..._
Any idea ?
Some say that I need to add virtualbox path to PATH . I have installed latest virtualbox and added install path to PATH, but this did not help  ##

**Comment by lnikell** [comment]
Hello @petitchamp! I'm not sure that it is depend on virtualbox. For example currently it working properly on all my machines without installation of virtualbox. What you have in your Vagrantfile? Are you sure that hyper V installed properly? For example could you create a new virtual machine via Hyper-V UI?
